### ISSUE TITLE
conflict with ERROR macro definition on windows with visual studio 2015

### ISSUE THREAD

**Issue by keedongpark** [couchbaselabs/libcouchbase-cxx#13]
In couchbase++h, following line has a conflict with macro ERROR.  
   enum State { STORE = 0, SUBMIT, DONE, ERROR };

In views.h, following definition has the same issue. 
enum class StaleMode { OK, FALSE, UPDATE_AFTER };

**Comment by mnunberg** [comment]
What's problem with `StaleMode`: is it `FALSE`?
