### ISSUE TITLE
Subdocument operations

### ISSUE THREAD

**Issue by zaycakitayca** [couchbaselabs/libcouchbase-cxx#23]
Are there any plans on adding libcouchbase subdocument support to this project?

**Comment by ingenthr** [comment]
None at the moment, but we'd certainly take a PR!

**Comment by zaycakitayca** [comment]
OK, I'll see if i'm able to implement this and send PR on success.

**Comment by ingenthr** [comment]
We can leave it open to track.  Thanks @zaycakitayca !

**Comment by ingenthr** [comment]
Oh, actually, a PR will create a new one.  My mistake.  Sorry!
