### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by shivshankardayal** [couchbaselabs/libcouchbase-cxx#5]
Although it is a header only library but when I try to build it, it builds the example.cpp file. Please fine the log below:

```
rhit@freedom:~/libcouchbase-cxx/build$ cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rhit/libcouchbase-cxx/build
rhit@freedom:~/libcouchbase-cxx/build$ make -j8
Scanning dependencies of target example                                                                                                                                          
[100%] Building CXX object CMakeFiles/example.dir/example.cpp.o                                                                                                                  
In file included from /home/rhit/libcouchbase-cxx/include/libcouchbase/couchbase++.h:772:0,
                 from /home/rhit/libcouchbase-cxx/example.cpp:1:
/home/rhit/libcouchbase-cxx/include/libcouchbase/couchbase++/client.inl.h: In member function ‘void Couchbase::DurableResponse<T>::handle_response(Couchbase::Client&, int, const lcb_RESPBASE*)’:
/home/rhit/libcouchbase-cxx/include/libcouchbase/couchbase++/client.inl.h:354:36: error: no match for ‘operator*’ (operand type is ‘Couchbase::EndureResponse’)
         EndureContext dctx(client, *m_dur, this, status);
                                    ^
CMakeFiles/example.dir/build.make:54: recipe for target 'CMakeFiles/example.dir/example.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by shivshankardayal** [comment]
Appears to be minor typo. Line 354 in client.inl.h is:

```c++
EndureContext dctx(client, *m_dur, this, status);
```

which should be

```c++
EndureContext dctx(client, m_dur, this, status);
```

and everything works fine.

In `class DurableResponse`  member `m_dur` is a plain value not a pointer and thus I do not see the need of dereference operator. But again I have spent like only 10 minutes on this and I might be wrong because of code in other files. Do you need a pull request for this?

**Comment by shivshankardayal** [comment]
However, when I run the `example` program I get following out:

``
$ ./bin/example 
Got status for store. Cas=c55e3c372914
Got value: { "v": 100.1, "list": [1,2,3,4,5,6,7], "talk": "About Foo." }
Got status for non-existent key: [0xd]: The key does not exist on the server
Got response for: Key
  Status: [0x0]: Success (Not an error)
  Value: Value
Endure Status: [0x17]: Client-Side timeout exceeded for operation. Inspect network conditions or increase the timeout
using options: limit=10&skip=10&descending=true&descending=false&
Got: 0 rows
Problem with query: [0x3b]: HTTP Operation failed. Inspect status code for details
Using async query..
View complete: 
  Status: [0x3b]: HTTP Operation failed. Inspect status code for details
  Body: {"error":"not_found","reason":"Design document _design/beer not found"}

Index creation: 
  Status: [0x0]: Success (Not an error)
  Body: {
    "requestID": "3271bae5-314f-439c-a5fe-6d231348d4ff",
    "signature": null,
    "results": [
    ],
    "errors": [
        {
            "code": 5000,
            "msg": "GSI CreatePrimaryIndex() - cause: Index #primary already exist."
        }
    ],
    "status": "errors",
    "metrics": {
        "elapsedTime": "754.922µs",
        "executionTime": "700.686µs",
        "resultCount": 0,
        "resultSize": 0,
        "errorCount": 1
    }
}

Row: {
            "$1": 770,
            "country": "France"
        }
Row: {
            "$1": 0
        }
Row: {
            "$1": 3930,
            "country": "United States"
        }
Row: {
            "$1": 2844,
            "country": "United Kingdom"
        }
``

So as you can see there are some errors. I am using Couchbase 4.1.0 and libcouchbase 2.5.5. All sample buckets are loaded. Am I missing anything? Should I give server some time to warm it up?

**Comment by shivshankardayal** [comment]
I found the problem that `beer-sample` is a different bucket while you were reusing the `default` bucket. I am pasting git diff for incorporating the changes:

```
 git diff
diff --git a/example.cpp b/example.cpp
index 656aeea..057e555 100644
--- a/example.cpp
+++ b/example.cpp
@@ -79,6 +79,13 @@ int main(int argc, const char **argv)
     h.remove("bar");
     h.remove("baz");
 
+    Couchbase::Client h1{"couchbase://localhost/beer-sample"};
+    Status rv1 = h1.connect();
+    if (!rv1.success()) {
+        cout << "Couldn't connect to '" << connstr << "'. "
+                << "Reason: " << rv1 << endl;
+        exit(EXIT_FAILURE);
+    }
     Status status;
     ViewCommand vCmd("beer", "brewery_beers");
     vCmd.include_docs();
@@ -89,7 +96,7 @@ int main(int argc, const char **argv)
 
     cout << "using options: " << vCmd.get_options() << endl;
 
-    ViewQuery query(h, vCmd, status);
+    ViewQuery query(h1, vCmd, status);
     if (!status) {
         cerr << "Error with view command: " << status << endl;
     }
@@ -115,7 +122,7 @@ int main(int argc, const char **argv)
 
     cout << "Using async query.." << endl;
     // Async
-    CallbackViewQuery asyncQuery(h, vCmd, status,
+    CallbackViewQuery asyncQuery(h1, vCmd, status,
         [](ViewRow&& row, CallbackViewQuery*) {
         cout << "Key: " << row.key() << endl;
         cout << "Value: " << row.value() << endl;
diff --git a/include/libcouchbase/couchbase++/client.inl.h b/include/libcouchbase/couchbase++/client.inl.h
index f4184e4..357adb3 100644
--- a/include/libcouchbase/couchbase++/client.inl.h
+++ b/include/libcouchbase/couchbase++/client.inl.h
@@ -351,7 +351,7 @@ DurableResponse<T>::handle_response(Client& client, int cbtype, const lcb_RESPBA
         m_op.handle_response(client, cbtype, rb);
         assert(m_op.done());
         Status status;
-        EndureContext dctx(client, *m_dur, this, status);
+        EndureContext dctx(client, m_dur, this, status);
         if (!status) {
             dur_bail(status);
             return;
```

**Comment by mnunberg** [comment]
Can you submit a pull request? :)

**Comment by shivshankardayal** [comment]
Submitted. :) I would like to help with this library development so if there is anything for which you may not have time please tell me. I can do small things for sure.

**Comment by shivshankardayal** [comment]
Closing this.
