### ISSUE TITLE
class Client has possible design problems

### ISSUE THREAD

**Issue by shivshankardayal** [couchbaselabs/libcouchbase-cxx#7]
class Client has a method deleted on line no. 766 which is

```cpp
Client(Client&) = delete;
```

Now the problem because of this is I was trying to adapt instance pool from libcouchbase library to C++ version. I cannot do a pop because if I write something like

```cpp
Couchasbe::Client h = instances.pop()
```

then I cannot do it. I would suggest to change the Client design to allow that to happen. I cannot cache any connected client to bucket because of that. May be my lack of knowledge is in my way.

**Comment by mnunberg** [comment]
This is deliberate. You are expected to use new Client, with std::shared_ptr. Client(Client&) would essentially destroy the old client or make a new client, which is not what is desired.

**Comment by shivshankardayal** [comment]
Thank you for fast response. I had thought of doing so but wanted to be sure if that is the right way because initializing a new client with another as argument is not good as lcb_destroy which gets called in dtor will not be called. Please correct me if I am wrong.

**Comment by mnunberg** [comment]
Right, hence the reason why Client(Client&) (and basically any copy or move constructor) is disabled

**Comment by shivshankardayal** [comment]
Also, I wanted to ask a question rather than creating a new issue. I am reading the documentation and code but you will know better. What are missing features in this library? Will it be forward compatible with new releases of libcouchbase? I am using it and will try to help if I find any problem.

**Comment by mnunberg** [comment]
I am not fully aware myself of all the features missing. I suppose the most major thing is figuring out how to expose a similar API (or something otherwise suitable) for non-C++11 compilers. Currently this being C++11-only limits the use of this library to new projects and small teams.

Otherwise, I believe the full gamut of functionality for libcouchbase with respect to key-value functionality is covered. Another minor issue might be the lack of a programmatic means by which to adjust client-side settings. Of course everything is always accessible using the raw C API, so I question how useful it would be to add C++ setting wrapper APIs, especially considering that the C version isn’t very difficult to use (though perhaps a bit primitive and low-level).

Regards,
Mark

**Comment by shivshankardayal** [comment]
It is very useful to provide wrappers, simply because it is much easier to use. I always get lost setting cookie to C callback functions. :P I do not care about C++98 neither should anyone else because C++11 is so much better. Legacy systems must upgrade their codebase or use C API. Key value functionality is the major part of API because views can always be accessed through a REST client.
I have not used Couchbase's indices much so I do not know.

However, you missed the second part of the question. Will this library remain compatible with new releases of libcouchbase?

**Comment by shivshankardayal** [comment]
Closing this.

**Comment by mnunberg** [comment]
libcouchbase has had the same API and ABI for over three years (we’ve added newer APIs, but never removed the older ones, so this library should remain compatible. I am very interested in this library (although I haven’t had enough time recently to invest more into it).

Indeed, this library’s main aim is to make cookie/callback handling much easier; and in fact this is the main benefit provided over the C interface.

With respect to legacy systems and older APIs: a large portion of the userbase of the C library consists of enterprise users with old systems; ultimately I would like to replace the traditional C API with the C++ API (the C API will still remain, but the C++ API will be made official and set as the “standard” API to use.

**Comment by shivshankardayal** [comment]
Thanks for all the information. I really appreciate you taking out time for helping me. Perhaps I can coerce my company to buy few licenses. :P
