### ISSUE TITLE
Problem including header files in multiple C++ files

### ISSUE THREAD

**Issue by shivshankardayal** [couchbaselabs/libcouchbase-cxx#8]
When I include the headers in more than one C++ files it gives multiple redefinition errors because the library is header only. I am solving this by marking the functions inline. Please tell me if it is correct approach and if it is I will submit a pull request.

**Comment by mnunberg** [comment]
I think this might be the correct solution. Are there any functions not marked as inline which do not have an inline definition?

**Comment by shivshankardayal** [comment]
There are many such functions. I have corrected for 5-6 functions which were giving trouble. A test suite might be a good solution to know all the problems.

**Comment by mnunberg** [comment]
Yes, i'm making such a test suite right now actually. it's not really a test suite per se. It's a simple CMake target with two object files.

**Comment by fileoffset** [comment]
This is currently blocking me also.

Multiple redefinitions everywhere. Unusable!

**Comment by fileoffset** [comment]
This is from a fresh clone, latest commit:

commit 80e176487a4c08bd918c0d95051e642848593489
Author: Oliver Kindernay <oliver.kindernay@gmail.com>
Date:   Tue Jan 24 17:08:16 2017 +0100

LastTest.log output:

check_redef" start time: Mar 28 17:56 AEDT
Output:
----------------------------------------------------------
Scanning dependencies of target redef_test
[ 33%] Building CXX object tests/CMakeFiles/redef_test.dir/redef_1.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/redef_test.dir/redef_2.cpp.o
[100%] Linking CXX executable ../bin/redef_test
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Get>::scheduler() const':
redef_2.cpp:(.text+0x0): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Get>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x0): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Store>::scheduler() const':
redef_2.cpp:(.text+0x10): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Store>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x10): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Touch>::scheduler() const':
redef_2.cpp:(.text+0x20): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Touch>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x20): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Remove>::scheduler() const':
redef_2.cpp:(.text+0x30): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Remove>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x30): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Stats>::scheduler() const':
redef_2.cpp:(.text+0x40): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Stats>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x40): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Unlock>::scheduler() const':
redef_2.cpp:(.text+0x50): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Unlock>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x50): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::Command<Couchbase::OpInfo::Counter>::scheduler() const':
redef_2.cpp:(.text+0x60): multiple definition of `Couchbase::Command<Couchbase::OpInfo::Counter>::scheduler() const'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x60): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::GetResponse::clear()':
redef_2.cpp:(.text+0x180): multiple definition of `Couchbase::GetResponse::clear()'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x180): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::GetResponse::handle_response(Couchbase::Client&, int, lcb_RESPBASE const*)':
redef_2.cpp:(.text+0x70): multiple definition of `Couchbase::GetResponse::handle_response(Couchbase::Client&, int, lcb_RESPBASE const*)'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x70): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::GetResponse::assign_first(Couchbase::GetResponse const&)':
redef_2.cpp:(.text+0x242): multiple definition of `Couchbase::GetResponse::assign_first(Couchbase::GetResponse const&)'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x242): first defined here
CMakeFiles/redef_test.dir/redef_2.cpp.o: In function `Couchbase::StatsResponse::handle_response(Couchbase::Client&, int, lcb_RESPBASE const*)':
redef_2.cpp:(.text+0x308): multiple definition of `Couchbase::StatsResponse::handle_response(Couchbase::Client&, int, lcb_RESPBASE const*)'
CMakeFiles/redef_test.dir/redef_1.cpp.o:redef_1.cpp:(.text+0x308): first defined here
collect2: error: ld returned 1 exit status
gmake[4]: *** [bin/redef_test] Error 1
gmake[3]: *** [tests/CMakeFiles/redef_test.dir/all] Error 2
gmake[2]: *** [tests/CMakeFiles/redef_test.dir/rule] Error 2
gmake[1]: *** [redef_test] Error 2
<end of output>
Test time =   1.25 sec
----------------------------------------------------------
Test Failed.
"check_redef" end time: Mar 28 17:56 AEDT
"check_redef" time elapsed: 00:00:01
----------------------------------------------------------
